// <auto-generated />
using System;
using GameDevsConnect.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace GameDevsConnect.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829150116_AddEnginesGenresAndProjectGitHubRepo")]
    partial class AddEnginesGenresAndProjectGitHubRepo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QuestId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UserId");

                    b.ToTable("contributions", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.QuestSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("UserId");

                    b.ToTable("quest_submissions", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.SubmissionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submission_files", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.SubmissionLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("submission_links", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Engines.Domain.Engine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("engines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e01"),
                            Name = "Unity"
                        },
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e02"),
                            Name = "Unreal Engine"
                        },
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e03"),
                            Name = "Godot"
                        },
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e04"),
                            Name = "GameMaker"
                        },
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e05"),
                            Name = "Construct"
                        },
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e06"),
                            Name = "RPG Maker"
                        },
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e07"),
                            Name = "Custom Engine"
                        },
                        new
                        {
                            Id = new Guid("f1a3f6b0-3b3f-4c1a-9f0e-1a2b3c4d5e08"),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Genres.Domain.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e01"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e02"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e03"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e04"),
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e05"),
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e06"),
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e07"),
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e08"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e09"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e0a"),
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e0b"),
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e0c"),
                            Name = "Visual Novel"
                        },
                        new
                        {
                            Id = new Guid("a2b4c6d8-1e2f-4a5b-8c6d-1a2b3c4d5e0d"),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Notifications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActivityEventId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EngineId")
                        .HasColumnType("uuid");

                    b.Property<string>("GitHubRepoFullName")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "Description" });

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.ProjectGenre", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("project_genres", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.ProjectTag", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("project_tags", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Quests.Domain.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxContributors")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "Description" });

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Quests.Domain.QuestAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("UserId");

                    b.ToTable("quest_assignments", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Quests.Domain.QuestSkill", b =>
                {
                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("quest_skills", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Skills.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b14f822f-009e-4bdd-8ee8-11f717c507e8"),
                            Category = "Programming",
                            Name = "Unity"
                        },
                        new
                        {
                            Id = new Guid("30e3205f-3abd-4b5d-89e9-9d4b32f282b6"),
                            Category = "Programming",
                            Name = "Unreal Engine"
                        },
                        new
                        {
                            Id = new Guid("2838e506-cb9c-408a-ac3e-2a525c3d982b"),
                            Category = "Programming",
                            Name = "Godot"
                        },
                        new
                        {
                            Id = new Guid("8e63ea09-22dc-4398-a5d5-c1bf8790867d"),
                            Category = "Programming",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("333877c3-9486-45bd-8b37-7f7ca9f7ee0a"),
                            Category = "Programming",
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("ccba96cf-0795-461b-8c92-99fcf4dd8bbe"),
                            Category = "Art3D",
                            Name = "Blender"
                        },
                        new
                        {
                            Id = new Guid("240d07c6-d557-4dc3-befc-77ed08584c17"),
                            Category = "Art3D",
                            Name = "Maya"
                        },
                        new
                        {
                            Id = new Guid("deccc28e-e8be-4cca-9f2b-7415f47e468b"),
                            Category = "Art2D",
                            Name = "Photoshop"
                        },
                        new
                        {
                            Id = new Guid("67aabe52-5d35-4e68-96da-ab51702eece9"),
                            Category = "Art2D",
                            Name = "2D Art"
                        },
                        new
                        {
                            Id = new Guid("439780f2-c1da-4f58-9207-f6efe2badfd7"),
                            Category = "Art3D",
                            Name = "3D Art"
                        },
                        new
                        {
                            Id = new Guid("a72cb020-7595-4f01-805e-56c1887492c2"),
                            Category = "Animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("6f77e0f9-75c3-48f3-aec3-fc8cc052b5c4"),
                            Category = "Animation",
                            Name = "Rigging"
                        },
                        new
                        {
                            Id = new Guid("f43e2b0d-5cbd-48de-bcf7-39b679195498"),
                            Category = "Audio",
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("81b3199c-400f-4c3c-a74a-49ffd46e521c"),
                            Category = "Audio",
                            Name = "Sound Design"
                        },
                        new
                        {
                            Id = new Guid("1e8cf9d9-bb76-4c08-9870-1df2f22bb6ca"),
                            Category = "Design",
                            Name = "Game Design"
                        },
                        new
                        {
                            Id = new Guid("3b563484-5b50-4943-814d-5b4fa647e5f5"),
                            Category = "Design",
                            Name = "Level Design"
                        },
                        new
                        {
                            Id = new Guid("145d0eaf-6309-448a-bb15-50a1523ecb24"),
                            Category = "Writing",
                            Name = "Writing"
                        });
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.ToTable("activity_events", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Follow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FollowerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FollowerUserId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Like", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.PostAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("post_attachments", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitHubAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Users.Domain.UserLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_links", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Users.Domain.UserSkill", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("user_skills", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Xp.Domain.XpTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("xp_transactions", (string)null);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.Contribution", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Quests.Domain.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Contributions.Domain.QuestSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.QuestSubmission", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Quests.Domain.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.SubmissionFile", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Contributions.Domain.QuestSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Contributions.Domain.SubmissionLink", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Contributions.Domain.QuestSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Notifications.Domain.Notification", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Social.Domain.ActivityEvent", null)
                        .WithMany()
                        .HasForeignKey("ActivityEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.Project", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Engines.Domain.Engine", null)
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.ProjectGenre", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Genres.Domain.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.ProjectMember", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Projects.Domain.ProjectTag", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Quests.Domain.Quest", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Quests.Domain.QuestAssignment", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Quests.Domain.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Quests.Domain.QuestSkill", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Quests.Domain.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Skills.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.ActivityEvent", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Comment", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Social.Domain.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Follow", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Like", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Social.Domain.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.Post", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Projects.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Social.Domain.PostAttachment", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Social.Domain.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Users.Domain.UserLink", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Users.Domain.UserSkill", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Skills.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDevsConnect.Api.Modules.Xp.Domain.XpTransaction", b =>
                {
                    b.HasOne("GameDevsConnect.Api.Modules.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
